### ISSUE TITLE
Attempted to kill init (AKA suicide in Linux)

### ISSUE THREAD

**Issue by ruppke** [linux-3ds/linux#72] opened 2022-03-06 21:15 UTC
When i boot into the Luma3ds chainloader I chose the Linux thing and it booted until It killed init and since I have Linux on a flash drive i can say that that is suicide for Linux but i don't know what to do now

**Comment by ruppke** [comment] 2022-03-09 23:49
No I downloaded all the files from uni-update

**Comment by shokifrend007** [comment] 2022-04-05 19:19
Hi, I couldn't reproduce your issue. Try using a file manager (like 3DShell from uni-updater) to look in the `/linux` directory. There should be 4 files there: `arm9linuxfw.bin`, `nintendo3ds_ctr.dtb`, `nintendo3ds_ktr.dtb` & `zImage`. Also look in `/luma/payloads` and check if `firm_linux_loader.firm` is there. Make sure that all these files are present, if not then download them from uni-updater. If they are present, they could be corrupt. Try deleting **all** of them and redownload them from uni-updater or the github repo.

**Comment by Wolfvak** [comment] 2022-04-07 11:19
@ruppke the files from universal updater are not maintained by us, you should do what the previous message says and try again.

**Comment by Wolfvak** [comment] 2022-10-02 14:23
Not enough info, nor any update from OP, closing

**Closed by Wolfvak** 2022-10-02 14:23 UTC
